### ISSUE TITLE
如何在nodejs服务端监听弹幕

### ISSUE THREAD

**Issue by Johnly1986** [champkeh/danmaku.bilibili#2]
你好，很棒的项目，但是我有一点疑问，如何在nodejs服务端获取弹幕？

**Comment by champkeh** [comment]
@Johnly1986 你好，这个项目是直接用的B站的客户端脚本改的，所以不支持NodeJS。

不过要支持也很简单，把WebSocket类替换成服务端的类，然后把相关的工具做一下兼容就行了。我抽时间兼容一下吧

**Comment by champkeh** [comment]
@Johnly1986 你好，我已经把功能重构成 websocket 在线服务了，你可以看一下这个文档[websocket重构](https://github.com/champkeh/danmaku.bilibili/blob/master/apis/refactor.md)
